# Generated by Django 5.1.5 on 2025-02-04 01:11

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(db_index=True, max_length=30, validators=[api.validators.validate_no_numeric_characters])),
                ('model', models.CharField(db_index=True, max_length=50)),
                ('year', models.IntegerField(db_index=True, validators=[api.validators.validate_year])),
                ('color', models.CharField(max_length=20, validators=[api.validators.validate_no_numeric_characters])),
                ('mileage', models.FloatField(validators=[api.validators.validate_positive])),
                ('price', models.FloatField(db_index=True, validators=[api.validators.validate_positive])),
                ('fuel_type', models.CharField(choices=[('G', 'Gasoline'), ('T', 'Ethanol'), ('D', 'Diesel'), ('E', 'Electric'), ('H', 'Hybrid')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rented', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='car_images/')),
            ],
            options={
                'indexes': [models.Index(fields=['make', 'model'], name='api_car_make_ba00ee_idx'), models.Index(fields=['year'], name='api_car_year_73396b_idx'), models.Index(fields=['price'], name='api_car_price_228d76_idx'), models.Index(fields=['created_at'], name='api_car_created_f34bf0_idx'), models.Index(fields=['make', 'model', 'year'], name='api_car_make_235cda_idx'), models.Index(fields=['make', 'model', 'price'], name='api_car_make_5242a4_idx'), models.Index(fields=['year', 'price'], name='api_car_year_5aac42_idx')],
            },
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
